name: Code Validation
on: 
    push:
    pull_request:
        branches:
            - main
            - publish
        paths:
            - 'components/**'
    
jobs:
    validation:
        runs-on: ubuntu-latest
        name: Validate Code Base 
        defaults:
            run:
                working-directory: ./components
        steps:
            - uses: actions/checkout@v4.1.7
            - name: Setup Node.js
              uses: actions/setup-node@v4.0.3
              with:
                  node-version: 20
            - name : Install pnpm
              uses: pnpm/action-setup@v4.0.0
              with:
                  version: 9.6.0
                  run_install: false
           
            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - uses: actions/cache@v4.0.2
              name: Setup pnpm cache
              with:
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-
        
            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile
            - name: Run Lint
              run: pnpm lint
            - name: Run Build
              run: pnpm build